

#include "Serializable.h"
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;


std::string Serializable::save()
{
  ptree tree;
  tree.put("type", this->type());
  this->saveHelper(tree);

  return PTreeToString(tree);
}



//takes a property tree, which should be generated by the subclass in the save method, and creates a json string from it
std::string Serializable::PTreeToString(ptree tree)
{
  std::ostringstream buf; 
  write_json (buf, tree, false);
  std::string json = buf.str();
  return json;
}

//takes a string which is presented in the load function, and produces a property tree, which can be used to fill up an objects values
ptree Serializable::StringtoPTree(std::string JSON)
{
  ptree tree;
  std::istringstream is (JSON);
  read_json (is, tree);
  return tree;
}
